-- MySQL Script generated by MySQL Workbench
-- 10/29/20 02:56:15
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema onboard
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema onboard
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `onboard` DEFAULT CHARACTER SET latin1 ;
USE `onboard` ;

-- -----------------------------------------------------
-- Table `onboard`.`admin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `onboard`.`admin` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(45) NOT NULL,
  `contraseña` VARCHAR(100) NOT NULL,
  `created_at` TIMESTAMP NULL,
  `update_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `onboard`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `onboard`.`usuarios` (
  `id` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `contraseña` VARCHAR(100) NOT NULL,
  `rol` VARCHAR(45) NOT NULL,
  `avatar` VARCHAR(45) NOT NULL,
  `direccion` VARCHAR(100) NULL,
  `ciudad` VARCHAR(45) NULL,
  `provincia` VARCHAR(45) NULL,
  `fecha` DATE NULL,
  `created_at` TIMESTAMP NULL,
  `update_at` TIMESTAMP NULL,
  `id_admin` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC),
  INDEX `id_admin_idx` (`id_admin` ASC),
  CONSTRAINT `id_admin`
    FOREIGN KEY (`id_admin`)
    REFERENCES `onboard`.`admin` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `onboard`.`categorias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `onboard`.`categorias` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `imagen` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `onboard`.`productos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `onboard`.`productos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  `precio` DECIMAL(5,2) NOT NULL,
  `descuento` INT NOT NULL,
  `descripcion` VARCHAR(300) NOT NULL,
  `imagen` VARCHAR(100) NOT NULL,
  `created_at` TIMESTAMP NULL,
  `update_at` TIMESTAMP NULL,
  `id_categorias` INT NULL,
  `id_admin` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `idCategorias_idx` (`id_categorias` ASC),
  INDEX `idAdmin_idx` (`id_admin` ASC),
  CONSTRAINT `idCategorias`
    FOREIGN KEY (`id_categorias`)
    REFERENCES `onboard`.`categorias` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idAdmin`
    FOREIGN KEY (`id_admin`)
    REFERENCES `onboard`.`admin` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `onboard`.`carritos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `onboard`.`carritos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_usuarios` INT NOT NULL,
  `id_productos` INT NOT NULL,
  `cantidad` INT NOT NULL,
  `fecha` DATE NULL,
  PRIMARY KEY (`id`),
  INDEX `idProductos_idx` (`id_productos` ASC),
  INDEX `idUsuarios_idx` (`id_usuarios` ASC),
  CONSTRAINT `idUsuarios`
    FOREIGN KEY (`id_usuarios`)
    REFERENCES `onboard`.`usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idProductos`
    FOREIGN KEY (`id_productos`)
    REFERENCES `onboard`.`productos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
